### ISSUE TITLE
Crash when running Romp library 

### ISSUE THREAD

**Issue by nbushehri** [zygyz/romp#2]
Hi. Using the master branch (commit 6a0ad6d), I can successfully build romp-lib and dyninst-client following the steps described in the readme file. However, I'm not able to test an application since an instrumented binary crashes with the following error: 

`./instrumented_app: symbol lookup error: /home/nader/code/romp_march/romp/pkgs-src/romp-lib/romp-install/lib/libomptrace.so: undefined symbol: elf_version`

I've attached the output of dyninst-client when instrumenting the DRB001-antidep1-orig-yes from the dataracebench since it might be useful in identifying what is causing this issue.

[dyninst-client-output.txt](https://github.com/zygyz/romp/files/2957692/dyninst-client-output.txt)

**Comment by zygyz** [comment]
Hi, Thanks for the report. The problem seems to be related with Dyninst's API calls. I will change the installation procedure. Instead of building all dependent libraries from scatch, I will switch to use Spack to install dependent libraries. Hopefully with this change, the Dyninst related issue could be solved.

**Comment by zygyz** [comment]
I have updated ROMP code and build process. Please pull the latest master branch and follow the readme.
